### ISSUE TITLE
Cannot paste into login window

### ISSUE THREAD

**Issue by theromit** [MehediH/Tweeten#3]
On macOS 10.12.5, I am unable to paste (for ex, my password) from clipboard. Also, right-click is disabled there.

**Comment by alphachung** [comment]
This issue is especially problematic for people who use password managers (e.g. 1Password, LastPass, etc.)

**Comment by MehediH** [comment]
Should be fixed on 4.0.1, please check and let me know guys.

**Comment by khaister** [comment]
I've downloaded the macOS version 4.0.1 and this issue still exists.

**Comment by MehediH** [comment]
Should be fixed on 4.0.2.
